2025CR560	7/11/2025	MikeR	Feature	"Add new report flags for HTTP POST Authentication. resultpostauthtypeid 0=none, 1=Basic resultpostauthparam1=username for Basic resultpostauthparam2=password for Basic"
2025CR551	7/8/2025	MikeR	Feature	FileUpload items do not typically have a good question in the item itself for AI. So, we need to use the AI Insructions as the question. 

2025CR546	7/8/2025	MikeR	Bug	"CandidateRefUtils.processSaveOrUploadResume() CCC.2 uploadedText.length=5762, rcCheckId=30304
Jul 07, 2025 1:04:16 PM com.tm2ref.service.LogService logIt
FINE: UERR BaseAiClient.sendApiPost() url=https://ts.hravatar.com/ai/webresources/airequest, payload={""tran"":""resumeparse"",""sourcetypeid"":1,""useridenc"":""1ykiz-tjA6c*"",""resumeid"":199,""autoupdate"":1}
java.net.SocketTimeoutException: Read timed out Changed timeout frmo 80 to 180 seconds."