2024CR1687	12/10/2024	mike	Bug	ref check completed page not responsive! 2024CR1688	12/10/2024	mike	Bug	3px bottom margin on buttons is not enough when the buttons wrap. Should be 5 px.
2024CR1690	12/10/2024	mike	Feature	Account-wide option to cc the authorizing user on all invitations and reminders
2024CR1691	12/10/2024	mike	Bug	"INE: UERR RcFacade.saveRcRater() RcRater{rcRaterId=0, rcCheckId=21959, userId=1860614}
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '21959-1860614' for key 'rcrater.rccheckuserid'
at com.tm2ref.ref.RcFacade.saveRcRater(RcFacade.java:678)
        at com.tm2ref.ref.RcCheckUtils.createRcRaterForCandidate(RcCheckUtils.java:821)
        at com.tm2ref.ref.RcCheckUtils.loadRcCheckForAdmin(RcCheckUtils.java:559)
        at com.tm2ref.ref.BaseRefUtils.performRcCheckStart(BaseRefUtils.java:1044)
        at com.tm2ref.ref.RefUtils.performSimpleEntry(RefUtils.java:172)"

2024CR1694	12/10/2024	mike	Bug	"FINE: RefExceptionHandler.handle() AAA.2 viewId=ViewRoot unavailable (FacesContext or FacesContext.viewRoot is null) fc=not null, Exception: jakarta.faces.FacesException: java.lang.RuntimeException: Error in multipart initialization, message=java.lang.RuntimeException: Error in multipart initialization
Dec 10, 2024 8:33:21 PM com.tm2ref.service.LogService logIt
FINE: UERR RefExceptionHandler.handle() AAA.2 Top-level Exception: jakarta.faces.FacesException: java.lang.RuntimeException: Error in multipart initialization root Cause Exception=java.io.EOFException

Incomplete file upload. Added a short delay in response processing for file uploads but that is probably not the issue."