2024CR1696	12/11/2024	mike	Bug	"Still getting UERR RefExceptionHandler.handle() AAA.2A Top-level Exception: jakarta.faces.FacesException: java.lang.RuntimeException: Error in multipart initialization root Cause Exception=java.io.EOFException java.io.EOFException         at org.glassfish.grizzly.nio.transport.TCPNIOTransport.read(TCPNIOTransport.java:575)         at org.glassfish.g
Also getting FINE: UERR RefExceptionHandler.handle() AAA.2B Top-level Exception: jakarta.faces.FacesException: java.lang.RuntimeException: Error in multipart initialization root Cause Exception=java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException
"
2024CR1697	12/11/2024	mike	Bug	"Dec 11, 2024 10:49:47 AM com.tm2ref.service.LogService logIt
FINE: UERR FileUploadFacade.saveRcUploadedUserFile() RcUploadedUserFile{rcUploadedUserFileId=0, rcCheckId=21815, rcRaterId=53427, rcItemId=0}
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] : org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '21815-53427-0-201' for key 'rcuploadeduserfile.rccheckid'
Error Code: 1062
Call: INSERT INTO rcuploadeduserfile (audiofilecontenttypeid,
at com.tm2ref.file.FileUploadFacade.saveRcUploadedUserFile(FileUploadFacade.java:85)
	at com.tm2ref.proctor.ProctorFileUploadThread.doFileUpload(ProctorFileUploadThread.java:394)
	at com.tm2ref.proctor.ProctorFileUploadThread.performFileUpload(ProctorFileUploadThread.java:183)
	at com.tm2ref.proctor.ProctorFileUploadServlet.doPost(ProctorFileUploadServlet.java:469)
"
2024CR1698	12/11/2024	mike	Bug	Ref not reporting candidate file uploads in status.